# comment
image: Visual Studio 2017

environment:
  nodejs_version: "10"

# Post-install test scripts!
test_script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # run tests
  - npm test

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - yarn

build_script:
  - yarn release -- --win

branches:
  only:
    - appveyor

deploy:
  provider: GitHub
  auth_token:
    secure: "$GH_TOKEN"
  on:
    branch: release

test: off