# comment
image: Visual Studio 2017

environment:
  nodejs_version: 10.14.2

# Post-install test scripts!
test_script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # run tests
  - npm test

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10.14.2 x64
  - ps: $env:package_version = "v" + (Get-Content -Raw -Path package.json | ConvertFrom-JSON).version 
  - ps: echo $env:package_version
  - ps: Update-AppveyorBuild -Version "$env:package_version:APPVEYOR_BUILD_NUMBER"
  - ps: npm -v
  - ps: node -v
  - ps: npm install --global --production windows-build-tools
  - npm install

build_script:
  - npm run build --win

branches:
  only:
    - appveyor

# If we want AppVeyor to handle deployment instead of electron-builder
# artifacts:
#   - path: dist
#     name: gitspeak-desktop

# deploy:
#   provider: GitHub
#   artifact: gitspeak-desktop
#   auth_token:
#     secure: 0EFPhJviDyp/yQqq+6te+ph61+3vCnmAcK7LUrHHY9a7ECXDTZqKIqDgszMkyo4B
#   on:
#     branch: release


test: off